import type { YearPlan } from "./types";

export const sampleData: YearPlan[] = [
  {
    year: "Freshman",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            code: "CSCI-UA 101",
            codeType: "CSCI-UA",
            title: "Intro to Computer Science",
            credits: 4,
            description:
              "Introduction to computer science concepts and programming.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "MATH-UA 121",
            codeType: "MATH-UA",
            title: "Calculus I",
            credits: 4,
            description: "First course in calculus sequence.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "EXPOS-UA 1",
            codeType: "EXPOS-UA",
            title: "Writing Workshop",
            credits: 4,
            description: "Academic writing workshop.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CORE-UA 100",
            codeType: "CORE-UA",
            title: "Cultural Foundations",
            credits: 4,
            description: "Introduction to cultural foundations.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            code: "CSCI-UA 102",
            codeType: "CSCI-UA",
            title: "Data Structures",
            credits: 4,
            description: "Fundamental data structures and algorithms.",
            prerequisites: ["CSCI-UA 101"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "MATH-UA 122",
            codeType: "MATH-UA",
            title: "Calculus II",
            credits: 4,
            description: "Second course in calculus sequence.",
            prerequisites: ["MATH-UA 121"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "PHYS-UA 91",
            codeType: "PHYS-UA",
            title: "Physics I",
            credits: 4,
            description: "Introductory physics course.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CORE-UA 200",
            codeType: "CORE-UA",
            title: "Societies & Social Sciences",
            credits: 2,
            description: "Introduction to social sciences.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "ZEROCREDIT",
            codeType: "ZERO",
            title: "Example Zero Credit",
            credits: 0,
            description: "Example zero credit course.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "Summer",
        courses: [],
      },
    ],
  },
  {
    year: "Sophomore",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            code: "CSCI-UA 201",
            codeType: "CSCI-UA",
            title: "Computer Systems Organization",
            credits: 4,
            description: "Computer architecture and systems.",
            prerequisites: ["CSCI-UA 102"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CSCI-UA 202",
            codeType: "CSCI-UA",
            title: "Operating Systems",
            credits: 4,
            description: "Operating systems concepts and design.",
            prerequisites: ["CSCI-UA 201"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "MATH-UA 140",
            codeType: "MATH-UA",
            title: "Linear Algebra",
            credits: 4,
            description: "Linear algebra and matrix theory.",
            prerequisites: ["MATH-UA 122"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CORE-UA 300",
            codeType: "CORE-UA",
            title: "Expressive Cultures",
            credits: 4,
            description: "Study of expressive cultures.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            code: "CSCI-UA 310",
            codeType: "CSCI-UA",
            title: "Basic Algorithms",
            credits: 4,
            description: "Algorithm design and analysis.",
            prerequisites: ["CSCI-UA 102"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CSCI-UA 380",
            codeType: "CSCI-UA",
            title: "Special Topics in CS",
            credits: 4,
            description: "Special topics in computer science.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "MATH-UA 325",
            codeType: "MATH-UA",
            title: "Analysis",
            credits: 4,
            description: "Real analysis course.",
            prerequisites: ["MATH-UA 122"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "Summer",
        courses: [
          {
            code: "INTERN-001",
            codeType: "INTERN",
            title: "Software Engineering Internship",
            credits: 0,
            description: "Summer internship experience.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
    ],
  },
  {
    year: "Junior",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            code: "CSCI-UA 453",
            codeType: "CSCI-UA",
            title: "Theory of Computation",
            credits: 4,
            description: "Formal languages, automata, and computability.",
            prerequisites: ["CSCI-UA 310"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CSCI-UA 480",
            codeType: "CSCI-UA",
            title: "Artificial Intelligence",
            credits: 4,
            description: "Introduction to AI concepts and techniques.",
            prerequisites: ["CSCI-UA 102"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "ELEC-001",
            codeType: "ELEC",
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            code: "CSCI-UA 473",
            codeType: "CSCI-UA",
            title: "Fundamentals of Machine Learning",
            credits: 4,
            description: "Machine learning fundamentals.",
            prerequisites: ["MATH-UA 140", "CSCI-UA 102"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CSCI-UA 467",
            codeType: "CSCI-UA",
            title: "Applied Internet Technology",
            credits: 4,
            description: "Web development and internet technologies.",
            prerequisites: ["CSCI-UA 102"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "ELEC-002",
            codeType: "ELEC",
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "Summer",
        courses: [],
      },
    ],
  },
  {
    year: "Senior",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            code: "CSCI-UA 490",
            codeType: "CSCI-UA",
            title: "Senior Project I",
            credits: 4,
            description: "First semester of senior capstone project.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "CSCI-UA 421",
            codeType: "CSCI-UA",
            title: "Computer Graphics",
            credits: 4,
            description: "Computer graphics and visualization.",
            prerequisites: ["MATH-UA 140"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "ELEC-003",
            codeType: "ELEC",
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            code: "CSCI-UA 491",
            codeType: "CSCI-UA",
            title: "Senior Project II",
            credits: 4,
            description: "Second semester of senior capstone project.",
            prerequisites: ["CSCI-UA 490"],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "ELEC-004",
            codeType: "ELEC",
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            code: "ELEC-005",
            codeType: "ELEC",
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            prerequisites: [],
            courseUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        term: "Summer",
        courses: [],
      },
    ],
  },
];
