import type { Id } from "@dev-team-fall-25/server/convex/_generated/dataModel";
import type { YearPlan } from "./types";

export const sampleData: YearPlan[] = [
  {
    year: "Freshman",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            _id: "jd7x8y9z0a1b2c3d4e5f6g7h" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 101",
            program: "CSCI-UA",
            level: 100,
            title: "Intro to Computer Science",
            credits: 4,
            description:
              "Introduction to computer science concepts and programming.",
            courseUrl: "#",
          },
          {
            _id: "kd7x8y9z0a1b2c3d4e5f6g7i" as Id<"courses">,
            _creationTime: Date.now(),
            code: "MATH-UA 121",
            program: "MATH-UA",
            level: 100,
            title: "Calculus I",
            credits: 4,
            description: "First course in calculus sequence.",
            courseUrl: "#",
          },
          {
            _id: "ld7x8y9z0a1b2c3d4e5f6g7j" as Id<"courses">,
            _creationTime: Date.now(),
            code: "EXPOS-UA 1",
            program: "EXPOS-UA",
            level: 0,
            title: "Writing Workshop",
            credits: 4,
            description: "Academic writing workshop.",
            courseUrl: "#",
          },
          {
            _id: "md7x8y9z0a1b2c3d4e5f6g7k" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CORE-UA 100",
            program: "CORE-UA",
            level: 100,
            title: "Cultural Foundations",
            credits: 4,
            description: "Introduction to cultural foundations.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            _id: "nd7x8y9z0a1b2c3d4e5f6g7l" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 102",
            program: "CSCI-UA",
            level: 100,
            title: "Data Structures",
            credits: 4,
            description: "Fundamental data structures and algorithms.",
            courseUrl: "#",
          },
          {
            _id: "od7x8y9z0a1b2c3d4e5f6g7m" as Id<"courses">,
            _creationTime: Date.now(),
            code: "MATH-UA 122",
            program: "MATH-UA",
            level: 100,
            title: "Calculus II",
            credits: 4,
            description: "Second course in calculus sequence.",
            courseUrl: "#",
          },
          {
            _id: "pd7x8y9z0a1b2c3d4e5f6g7n" as Id<"courses">,
            _creationTime: Date.now(),
            code: "PHYS-UA 91",
            program: "PHYS-UA",
            level: 0,
            title: "Physics I",
            credits: 4,
            description: "Introductory physics course.",
            courseUrl: "#",
          },
          {
            _id: "qd7x8y9z0a1b2c3d4e5f6g7o" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CORE-UA 200",
            program: "CORE-UA",
            level: 200,
            title: "Societies & Social Sciences",
            credits: 2,
            description: "Introduction to social sciences.",
            courseUrl: "#",
          },
          {
            _id: "rd7x8y9z0a1b2c3d4e5f6g7p" as Id<"courses">,
            _creationTime: Date.now(),
            code: "ZEROCREDIT",
            program: "ZERO",
            level: 0,
            title: "Example Zero Credit",
            credits: 0,
            description: "Example zero credit course.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "Summer",
        courses: [],
      },
    ],
  },
  {
    year: "Sophomore",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            _id: "sd7x8y9z0a1b2c3d4e5f6g7q" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 201",
            program: "CSCI-UA",
            level: 200,
            title: "Computer Systems Organization",
            credits: 4,
            description: "Computer architecture and systems.",
            courseUrl: "#",
          },
          {
            _id: "td7x8y9z0a1b2c3d4e5f6g7r" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 202",
            program: "CSCI-UA",
            level: 200,
            title: "Operating Systems",
            credits: 4,
            description: "Operating systems concepts and design.",
            courseUrl: "#",
          },
          {
            _id: "ud7x8y9z0a1b2c3d4e5f6g7s" as Id<"courses">,
            _creationTime: Date.now(),
            code: "MATH-UA 140",
            program: "MATH-UA",
            level: 100,
            title: "Linear Algebra",
            credits: 4,
            description: "Linear algebra and matrix theory.",
            courseUrl: "#",
          },
          {
            _id: "vd7x8y9z0a1b2c3d4e5f6g7t" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CORE-UA 300",
            program: "CORE-UA",
            level: 300,
            title: "Expressive Cultures",
            credits: 4,
            description: "Study of expressive cultures.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            _id: "wd7x8y9z0a1b2c3d4e5f6g7u" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 310",
            program: "CSCI-UA",
            level: 300,
            title: "Basic Algorithms",
            credits: 4,
            description: "Algorithm design and analysis.",
            courseUrl: "#",
          },
          {
            _id: "xd7x8y9z0a1b2c3d4e5f6g7v" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 380",
            program: "CSCI-UA",
            level: 300,
            title: "Special Topics in CS",
            credits: 4,
            description: "Special topics in computer science.",
            courseUrl: "#",
          },
          {
            _id: "yd7x8y9z0a1b2c3d4e5f6g7w" as Id<"courses">,
            _creationTime: Date.now(),
            code: "MATH-UA 325",
            program: "MATH-UA",
            level: 300,
            title: "Analysis",
            credits: 4,
            description: "Real analysis course.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "Summer",
        courses: [
          {
            _id: "zd7x8y9z0a1b2c3d4e5f6g7x" as Id<"courses">,
            _creationTime: Date.now(),
            code: "INTERN-001",
            program: "INTERN",
            level: 0,
            title: "Software Engineering Internship",
            credits: 0,
            description: "Summer internship experience.",
            courseUrl: "#",
          },
        ],
      },
    ],
  },
  {
    year: "Junior",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            _id: "ae7x8y9z0a1b2c3d4e5f6g7y" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 453",
            program: "CSCI-UA",
            level: 400,
            title: "Theory of Computation",
            credits: 4,
            description: "Formal languages, automata, and computability.",
            courseUrl: "#",
          },
          {
            _id: "be7x8y9z0a1b2c3d4e5f6g7z" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 480",
            program: "CSCI-UA",
            level: 400,
            title: "Artificial Intelligence",
            credits: 4,
            description: "Introduction to AI concepts and techniques.",
            courseUrl: "#",
          },
          {
            _id: "ce7x8y9z0a1b2c3d4e5f6g8a" as Id<"courses">,
            _creationTime: Date.now(),
            code: "ELEC-001",
            program: "ELEC",
            level: 0,
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            _id: "de7x8y9z0a1b2c3d4e5f6g8b" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 473",
            program: "CSCI-UA",
            level: 400,
            title: "Fundamentals of Machine Learning",
            credits: 4,
            description: "Machine learning fundamentals.",
            courseUrl: "#",
          },
          {
            _id: "ee7x8y9z0a1b2c3d4e5f6g8c" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 467",
            program: "CSCI-UA",
            level: 400,
            title: "Applied Internet Technology",
            credits: 4,
            description: "Web development and internet technologies.",
            courseUrl: "#",
          },
          {
            _id: "fe7x8y9z0a1b2c3d4e5f6g8d" as Id<"courses">,
            _creationTime: Date.now(),
            code: "ELEC-002",
            program: "ELEC",
            level: 0,
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "Summer",
        courses: [],
      },
    ],
  },
  {
    year: "Senior",
    terms: [
      {
        term: "Fall",
        courses: [
          {
            _id: "ge7x8y9z0a1b2c3d4e5f6g8e" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 490",
            program: "CSCI-UA",
            level: 400,
            title: "Senior Project I",
            credits: 4,
            description: "First semester of senior capstone project.",
            courseUrl: "#",
          },
          {
            _id: "he7x8y9z0a1b2c3d4e5f6g8f" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 421",
            program: "CSCI-UA",
            level: 400,
            title: "Computer Graphics",
            credits: 4,
            description: "Computer graphics and visualization.",
            courseUrl: "#",
          },
          {
            _id: "ie7x8y9z0a1b2c3d4e5f6g8g" as Id<"courses">,
            _creationTime: Date.now(),
            code: "ELEC-003",
            program: "ELEC",
            level: 0,
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "J-Term",
        courses: [],
      },
      {
        term: "Spring",
        courses: [
          {
            _id: "je7x8y9z0a1b2c3d4e5f6g8h" as Id<"courses">,
            _creationTime: Date.now(),
            code: "CSCI-UA 491",
            program: "CSCI-UA",
            level: 400,
            title: "Senior Project II",
            credits: 4,
            description: "Second semester of senior capstone project.",
            courseUrl: "#",
          },
          {
            _id: "ke7x8y9z0a1b2c3d4e5f6g8i" as Id<"courses">,
            _creationTime: Date.now(),
            code: "ELEC-004",
            program: "ELEC",
            level: 0,
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            courseUrl: "#",
          },
          {
            _id: "le7x8y9z0a1b2c3d4e5f6g8j" as Id<"courses">,
            _creationTime: Date.now(),
            code: "ELEC-005",
            program: "ELEC",
            level: 0,
            title: "Elective Course",
            credits: 4,
            description: "General elective course.",
            courseUrl: "#",
          },
        ],
      },
      {
        term: "Summer",
        courses: [],
      },
    ],
  },
];
